-- V1.0.0: CREATE ROLES AND USERS
-- 1. CREATE UUID EXTENSION IF DONT HAVE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CREATE ROLES TABLE
CREATE TABLE roles (
    id BIGSERIAL  PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

-- 3. CREATE USERS TABLE

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

        email VARCHAR(100) UNIQUE NOT NULL,
        username VARCHAR(100),
        password VARCHAR(255),

        provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',

        --(FK)
        role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,

        is_active BOOLEAN DEFAULT TRUE,
        last_login TIMESTAMP WITHOUT TIME ZONE,

        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_user_email_unique ON users (email);